In [ ]:
## 2.14

In [2]:
import numpy as np
a = np.array([1, 2, 3, 4])
print(a)

[1 2 3 4]


In [36]:
import time

a = np.random.rand(1000000)
b = np.random.rand(1000000)

tic = time.time()
c = np.dot(a, b)
toc = time.time()

print(c)
print("Verctorized version:" + str(1000*(toc-tic)) + "ms")

c = 0
tic = time.time()
for i in range(1000000):
    c += a[i]*b[i]
toc = time.time()

print(c)
print("For loop:" + str(1000*(toc-tic))+"ms")

249965.4023553912
Verctorized version:1.003265380859375ms
249965.40235539732
For loop:621.636152267456ms


In [38]:
## 2.13

In [39]:
import numpy as np

A = np.array([[56.0, 0.0, 4.4, 68.0],
             [1.2, 104.0, 52.0, 8.0],
             [1.8, 135.0, 99.0, 0.9]])

print(A)

[[ 56.    0.    4.4  68. ]
 [  1.2 104.   52.    8. ]
 [  1.8 135.   99.    0.9]]


In [41]:
cal = A.sum(axis=0)
print(cal)

[ 59.  239.  155.4  76.9]


In [43]:
percentage = 100 * A/cal.reshape(1,4)
print(percentage)

[[94.91525424  0.          2.83140283 88.42652796]
 [ 2.03389831 43.51464435 33.46203346 10.40312094]
 [ 3.05084746 56.48535565 63.70656371  1.17035111]]


In [44]:
import numpy as np
a = np.random.rand(5)

print(a) #这里的a既不是行向量，也不是列向量

[0.56220363 0.29334819 0.21940352 0.81075489 0.09298483]


In [47]:
print(a.shape) #秩为1的数组

(5,)


In [48]:
print(a.T) # 转秩是其本身

[0.56220363 0.29334819 0.21940352 0.81075489 0.09298483]


In [49]:
print(np.dot(a, a.T))

1.1162336418858094


In [50]:
b = np.random.rand(5, 1) # 这里的b是列向量

In [51]:
print(b)

[[0.63766338]
 [0.96639895]
 [0.71440352]
 [0.87130729]
 [0.32127465]]


In [52]:
print(b.T)

[[0.63766338 0.96639895 0.71440352 0.87130729 0.32127465]]


In [53]:
print(np.dot(b, b.T))

[[0.40661459 0.61623722 0.45554896 0.55560076 0.20486508]
 [0.61623722 0.93392693 0.69039881 0.84203045 0.31047949]
 [0.45554896 0.69039881 0.51037239 0.622465   0.22951974]
 [0.55560076 0.84203045 0.622465   0.7591764  0.27992895]
 [0.20486508 0.31047949 0.22951974 0.27992895 0.1032174 ]]
